# Generated by Django 5.1.3 on 2024-11-16 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='name',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='blog.post')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('post', 'ip_address')},
            },
        ),
    ]
